### PR TITLE
Update mbdata for MusicBrainz schema change 2022-05-16

### PR DESCRIPTION
**Pull request by amCap1712**
This PR contains the commits in #46 as well so ideally that PR should be merged first. The only major change in this PR is adding     mbdata/sql/CreateTypes.sql to update_models.py script because the CREATE TYPE statements have now been separated into a separate file (earlier this used to be in CreateTables.sql). The rest is only running the update_sql.py and update_models.py.

### CODE REVIEW

**Comment by sfussenegger** [comment]
Thanks a lot for your help!

You could include the update instructions for others in README.rst:

```
mbslave psql -f updates/schema-change/27.mirror.sql
echo 'UPDATE replication_control SET current_schema_sequence = 27;' | mbslave psql
```

**Comment by amCap1712** [comment]
Thanks done. I also noticed that older schema change files have been renamed. For instance, 26.slave.sql -> 26.mirror.sql. Thoughts on whether the instructions for older versions should be edited accordingly  (would work with this version of mbdata) or left as is (would work with older versions of mbdata)?

**Comment by bt0r** [comment]
@lalinsky @sfussenegger Any comments on this PR ? 👀 

Thank you guys for your work

**Comment by sfussenegger** [comment]
@bt0r we've used this branch to update and aren't seeing any issues afaik

**Comment by lalinsky** [comment]
@amCap1712 Thank you!

**Pull request merged**
